pipeline {
    agent {
        label 'docker-jenkins-agent'  // Use the Docker template label
    }
    environment {
        DOCKER_IMAGE = "amundead/nginx-hello-world"   // Docker image with tag
        DOCKER_TAG = "v1.07"
        DOCKER_FULL_IMAGE = "${DOCKER_IMAGE}:${DOCKER_TAG}"
        // KUBECONFIG = "/home/jenkins/agent/k8s-dev/k3s.yaml"  // Path to your KUBECONFIG
        NAMES_SPACE = "dev-app-awam"  // Namespace for deployment in k8s
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "https://github.com/amundead/test-repo.git"  // Clone your GitHub repo
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_FULL_IMAGE .'  // Build Docker image
            }
        }
        
        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials-id', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR')]) {
                        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                        sh 'docker push $DOCKER_FULL_IMAGE'  // Push Docker image to Docker Hub
                    }
                }
            }
        }

        stage('Check Files') {
            steps {
                sh 'ls -R'  // List all files in the workspace to verify the structure
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                script {
                    // Update manifest with new image tag
                    sh "sed -i 's|{{DOCKER_TAG}}|$DOCKER_TAG|g' /home/jenkins/workspace/CI-CD-hellowordtomyhome/deploy/deployment.yaml"
                    // You may need to uncomment and adjust these lines as needed
                    // sh "sed -i 's|{{NAME_DEPLOY}}|$NAME_DEPLOY|g' /path/to/deployment.yaml"
                    // sh "sed -i 's|{{NAMES_SPACE}}|$NAMES_SPACE|g' /path/to/deployment.yaml"

                    // Commit and push changes to Git
                    dir('/home/jenkins/workspace/CI-CD-hellowordtomyhome/deploy') { // Change to the directory containing the deployment.yaml
                        sh """
                        git config user.name "jenkins"
                        git config user.email "jenkins@mycompany.com"
                        git add deployment.yaml
                        git commit -m 'Update image to ${DOCKER_FULL_IMAGE}'
                        git push origin main
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment to Kubernetes development cluster successful!'
        }
        failure {
            echo 'Deployment failed! haha'
        }
    }
}
