apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-php
  namespace: prod-win-awam
  labels:
    app: win-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: win-php
  template:
    metadata:
      labels:
        app: win-php
    spec:
      tolerations:
      - key: "kubernetes.io/os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"
      containers:
      - name: win-php
        image: bakul.mod.gov.my/testing-app/win-php:v1.04
        imagePullPolicy: Always
        ports:
        - containerPort: 80

#---
#apiVersion: v1
#kind: Service
#metadata:
  #name: node-helloworld-service
  #namespace: dev-app-awam
#spec:
  #type: ClusterIP  # Set the service type to ClusterIP
  #selector:
    #app: node-helloworld
  #ports:
    #- protocol: TCP
      #port: 8181       # The port that will be exposed inside the cluster
      #targetPort: 80 # The port that the container listens on
---
apiVersion: v1
kind: Service
metadata:
  name: win-php-loadbalancer
  namespace: prod-win-awam
spec:
  type: LoadBalancer  # Set the service type to LoadBalancer
  selector:
    app: win-php
  ports:
    - protocol: TCP
      port: 8181       # The port exposed to the external world
      targetPort: 80 # The port that the container listens on
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
  #name: hello-world-ingress
  #namespace: dev-app-awam
  #annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
  #rules:
    #- host: hello.local.my  # The hostname to be used
      #http:
        #paths:
          #- path: /
            #pathType: Prefix
            #backend:
              #service:
                #name: hello-world-service  # The name of the service created earlier
                #port:
                  #number: 80  # The port exposed by the service
