apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{DOCKER_IMAGE}}   # Pulls the latest Nginx image
        ports:
        - containerPort: 80   # Nginx listens on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: LoadBalancer   # Specifies a LoadBalancer type service
  ports:
  - port: 80           # Port on the Nginx container
    targetPort: 80     # Nginx listens on 80
    nodePort: 8080     # The node port that will map to the load balancer
  selector:
    app: nginx         # Matches the app label of the Nginx pods
