apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev-app-awam 
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{DOCKER_IMAGE}}   # Pulls the latest Nginx image
        ports:
        - containerPort: 80   # Nginx listens on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
  namespace: dev-app-awam  # Specify the namespace
spec:
  type: ClusterIP  # Set the service type to ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80       # The port that will be exposed inside the cluster
      targetPort: 80 # The port that the container listens on
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  namespace: dev-app-awam  # Specify the namespace
spec:
  type: LoadBalancer  # Set the service type to LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080       # The port exposed to the external world
      targetPort: 80 # The port that the container listens on
