version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-12-13T22-19-12Z.fips
    container_name: minio
    ports:
      - "9000:9000" # MinIO API access
      - "9001:9001" # MinIO Console access
    environment:
      - MINIO_ROOT_USER=admin # Replace with your preferred username
      - MINIO_ROOT_PASSWORD=strongpassword123 # Replace with your preferred password
    volumes:
      - minio-data:/data # Persistent data storage
    command: server /data --console-address ":9001" # MinIO server with console
    networks:
      - minio-network

volumes:
  minio-data:
    driver: local

networks:
  minio-network:
    driver: bridge
