services:
  web:
    image: dwchiang/nginx-php-fpm:8.4.1-fpm-alpine3.20-nginx-1.27.1
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/public/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
